import { useEffect, useState } from 'react';
import { 
  AlertTriangle, 
  CheckCircle, 
  Clock, 
  Trash2, 
  Filter,
  ShieldAlert,
  ArrowRight,
  Loader2,
  TrendingUp
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { api } from '../lib/api.js';
import { toast } from 'sonner';

export default function Alerts() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);

  const fetchAlerts = () => {
    setLoading(true);
    api.get('/alerts')
      .then(res => setAlerts(res.data.alerts))
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const resolveAlert = async (id: string) => {
    try {
      setProcessingId(id);
      await api.patch(`/alerts/${id}/resolve`, {});
      toast.success('Alert Investigated');
      setAlerts(prev => prev.map(a => a.id === id ? { ...a, isResolved: true, resolvedAt: new Date() } : a));
    } catch (error) {
      console.error(error);
      toast.error('Resolution failed');
    } finally {
      setProcessingId(null);
    }
  };

  const escalateAlert = async (id: string) => {
    try {
      setProcessingId(id);
      await api.patch(`/alerts/${id}/escalate`, {});
      toast.warning('Security Escalated');
      setAlerts(prev => prev.map(a => a.id === id ? { ...a, severity: 'CRITICAL' } : a));
    } catch (error) {
      console.error(error);
      toast.error('Escalation failed');
    } finally {
      setProcessingId(null);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tighter flex items-center gap-3">
             <ShieldAlert className="w-8 h-8 text-rose-600" />
             CRITICAL MONITORING CENTER
          </h1>
          <p className="text-slate-500 text-sm font-medium italic">High-priority alerts generated by medical intelligence engine.</p>
        </div>
        <div className="flex gap-2">
           <button className="px-3 py-1.5 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold hover:bg-slate-200 transition-all flex items-center gap-2">
             <Filter className="w-3 h-3" /> All Severity
           </button>
           <button className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-black uppercase tracking-widest hover:bg-slate-800 transition-all">Clear Resolved</button>
        </div>
      </div>

      <div className="space-y-4">
        {loading ? (
          <div className="p-20 text-center text-slate-400 font-bold uppercase tracking-widest animate-pulse">Initializing Security Protocols...</div>
        ) : alerts.length === 0 ? (
          <div className="bg-white p-12 rounded-3xl border-2 border-dashed border-slate-200 text-center space-y-4 flex flex-col items-center">
             <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center">
                <CheckCircle className="w-8 h-8 text-emerald-500" />
             </div>
             <div>
                <h3 className="font-bold text-slate-900 text-lg">System Status: Secure</h3>
                <p className="text-slate-500 text-sm">No critical anomalies detected in current physiological data streams.</p>
             </div>
          </div>
        ) : (
          <AnimatePresence mode="popLayout">
            {alerts.map((alert) => (
              <motion.div 
                layout
                key={alert.id}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className={`group relative bg-white p-6 rounded-2xl border-2 transition-all ${
                   alert.isResolved 
                    ? 'border-slate-100 opacity-60' 
                    : alert.severity === 'CRITICAL' 
                      ? 'border-rose-100 shadow-lg shadow-rose-500/5 hover:border-rose-300' 
                      : 'border-amber-100 hover:border-amber-300 shadow-lg shadow-amber-500/5'
                }`}
              >
                <div className="flex items-start gap-5">
                   <div className={`w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 shadow-sm ${
                      alert.isResolved 
                        ? 'bg-slate-100 text-slate-400' 
                        : alert.severity === 'CRITICAL' 
                          ? 'bg-rose-600 text-white' 
                          : 'bg-amber-500 text-white'
                   }`}>
                      <AlertTriangle className="w-6 h-6" />
                   </div>

                   <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-3 mb-1">
                         <h3 className={`font-black tracking-tight ${alert.isResolved ? 'text-slate-500' : 'text-slate-900 group-hover:text-blue-700'} transition-colors`}>{alert.message}</h3>
                         <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full ring-1 ${
                            alert.severity === 'CRITICAL' ? 'bg-rose-50 text-rose-700 ring-rose-200' : 'bg-amber-50 text-amber-700 ring-amber-200'
                         }`}>{alert.severity}</span>
                      </div>
                      
                      <div className="flex items-center gap-3 text-xs font-bold text-slate-500 mb-4 uppercase tracking-tighter">
                         <span className="flex items-center gap-1.5"><Clock className="w-3 h-3" /> {new Date(alert.createdAt).toLocaleString()}</span>
                         <span className="w-1 h-1 rounded-full bg-slate-300"></span>
                         <span className="text-blue-600">ATHLETE: {alert.athlete.name}</span>
                      </div>

                      {!alert.isResolved && (
                        <div className="flex gap-2">
                           <button 
                             disabled={processingId === alert.id}
                             onClick={() => resolveAlert(alert.id)}
                             className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg text-[10px] font-black uppercase tracking-widest hover:bg-slate-800 hover:scale-105 transition-all active:scale-95 disabled:opacity-50"
                           >
                              {processingId === alert.id ? <Loader2 className="w-3 h-3 animate-spin" /> : <ArrowRight className="w-3 h-3" />}
                              Investigated
                           </button>
                           {alert.severity !== 'CRITICAL' && (
                             <button 
                               disabled={processingId === alert.id}
                               onClick={() => escalateAlert(alert.id)}
                               className="flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-700 border border-rose-100 rounded-lg text-[10px] font-black uppercase tracking-widest hover:bg-rose-100 transition-all active:scale-95 disabled:opacity-50"
                             >
                                <TrendingUp className="w-3 h-3" /> Escalate
                             </button>
                           )}
                           <button className="px-4 py-2 bg-slate-100 text-slate-600 rounded-lg text-[10px] font-black uppercase tracking-widest hover:bg-slate-200 transition-all">Reject</button>
                        </div>
                      )}
                   </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        )}
      </div>
    </div>
  );
}
